spring:
  application:
    name: admin-service
  datasource:
      url: jdbc:mysql://localhost:3306/userservice
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
  jpa:
   hibernate:
    ddl-auto: update
   show-sql: true
   database-platform: org.hibernate.dialect.MySQL5Dialect   
server:
  port: 8900
  error:
    whitelabel:
      enabled: false
  
